### ISSUE TITLE
The size between object need to detect and images

### ISSUE THREAD

**Issue by Coderxiaobai1** [Cli98/anchor_computation_tool#13]
Hi, Bro. It haunts me much. The question is as followed:
    I am using the images of my uav. And the image size is 3840*2160, the object i want to detect is 94*325 or 236*938, so is the object small or mid or large?(According to the coco, it is absolutely large cause it is bigger than 96*96, but how am i going to process the 3840*2160 images when put it into yolo series or ssd?)
    I will appreciate it if can i get your reply soon. Thanks.

**Comment by Cli98** [comment]
@Coderxiaobai1 This is definitely a large image and the scale of object is large (>128*128) and I do believe that you need some aerial image based algorithm to take care of it, instead of applying yolo stuff directly.

One possible way is to crop image and only take crops that contains objects. Try this one if you are interested. 

https://github.com/Cli98/DMNet

Thank you,

**Comment by Coderxiaobai1** [comment]
Thank you so much bro, i know that you can solve my problem.

**Comment by Cli98** [comment]
@Coderxiaobai1 Good luck. I will close this issue by now. Feel free to reopen if needed.
