### ISSUE TITLE
what the ****!

### ISSUE THREAD

**Issue by WIKI2020** [Cli98/anchor_computation_tool#8]
my dataset is:(according to Yet-Another-EfficientDet-Pytorch)

dataset
      object
          annotations
          train
          val
 
And I think all the settings are right 

when running program：
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loading image with numpy array
Image id:  0
Loading image with numpy array
Image id:  1
Loading image with numpy array
Image id:  2
Loading image with numpy array
Image id:  3
 
No task results，What's the problem？？？？？？？？？？

**Comment by Cli98** [comment]
@huangweiji2019 You use 0 sec to load your image, so clearly the issue is, the program is not able to locate where your annotations file is.
To resolve, You need to modify anchor file and change train/val field to the name of your anchor. Or, a quicker way to fix this, you need to change your anchor file to "train.json" and "val.json". In the meanwhile, this repo only support coco annotation for now. 

And please consider changing your title, * word may lead to confusion.

**Comment by WIKI2020** [comment]
@Cli98 I put your code in Yet-Another-EfficientDet-Pytorch
and
----------myproject
--------------train
-----------------xxx.jpg
                    .....
--------------val
-----------------xxx.jpg
                    .....
--------------annotations
-----------------train.json
-----------------val.json
----------projects
--------------myproject.yaml
python anchor_inspector.py -dataset_path ./datasets/myproject -project_name ./projects/mypoject --output-dir ./

I think all the settings are right, there's a problem with your code

**Comment by Cli98** [comment]
@huangweiji2019 
Are you typing correct command?

python anchor_inspector.py -dataset_path ./datasets/myproject -project_name ./projects/mypoject --output-dir ./

There is a typo in your project_name parameter, "**mypoject**". Please do not blame others for your careless mistake.

And please edit your title to remove "*" word.

**Comment by Cli98** [comment]
Issue closed. Please reopen if you have any other questions.
